### ISSUE TITLE
Entity annotation breaks with rasa X

### ISSUE THREAD

**Issue by juliamendoim** [BeWe11/rasa_composite_entities#10]

**Comment by juliamendoim** [comment]
I'm trying to use rasa X to scale the training process, but when I try to use the NLU Training tool, utterances with composite_entities appear repeated and can't be manipulated.

![25446e1662bb9d2aa01550a1d8753cd032d3a54c](https://user-images.githubusercontent.com/33423699/62472693-93458280-b79f-11e9-9c54-cd1345311c04.png)

**Comment by BeWe11** [comment]
hey @juliamendoim,

unfortunately, I have no time right now to work on a better integration between rasa X and this component. I will leave this issue open for reference but it is unlikely that this will be fixed anytime soon.

**Comment by BeWe11** [comment]
Much has changed for Rasa since this issue has been opened, I'm gonna close this for now until someone wants it to be reopened.
