### ISSUE TITLE
Issue while training Rasa NLU with Rasa1.3.3

### ISSUE THREAD

**Issue by NomanSaleem4** [BeWe11/rasa_composite_entities#12]
![a](https://user-images.githubusercontent.com/17758473/67631929-993e9180-f8be-11e9-8ef6-3439883b8384.png)

**Comment by nbeuchat** [comment]
I do have the same issue, also using rasa 1.3.3

**Comment by nbeuchat** [comment]
Rasa moved the `list_files` function to another module: https://github.com/RasaHQ/rasa/blob/b8fd71c01207ce33ca11b2ee65320a769df61c8e/rasa/utils/io.py

Therefore, the import should be `from rasa.utils.io import list_files` (not sure if that's the only breaking change though)

**Comment by BeWe11** [comment]
@nbeuchat thank you for pointing me to the correct location, I've released a new version (0.4.5) that anticipates the changed import location of these utility methods.

**Comment by NomanSaleem4** [comment]
getting this issue now. 
![a](https://user-images.githubusercontent.com/17758473/69860929-0cba3100-12b9-11ea-98b2-dceae80a646a.png)

**Comment by BeWe11** [comment]
Hey @NomanSaleem4,

Can you please try updating rasa and rasa-composite-entities and then running the example training from this repo? If that works, you might have faulty training file.

**Comment by NomanSaleem4** [comment]
i am using rasa==1.3.3 and the updated versio of composite entities, when i use rasa train nlu it works but when i use a my own script to train nlu model with composite entities it does not

**Comment by BeWe11** [comment]
Can you post your train file here? or at least the part that defines the composite entities?

**Comment by NomanSaleem4** [comment]
@BeWe11  i tried rasa run instead of training through .py and it worked

**Comment by BeWe11** [comment]
@NomanSaleem4 great that it works now! There is an open issue https://github.com/BeWe11/rasa_composite_entities/issues/9 about problems loading the component when using the python API.

**Comment by NomanSaleem4** [comment]
Great hope that will be resolved soon. Thanks for the quick response.
