### ISSUE TITLE
Composite Entities training for multiple files is not handled

### ISSUE THREAD

**Issue by AfrinKhanam** [BeWe11/rasa_composite_entities#2]
I'm trying to find out all the possibilities to train composite entities for multiple files. Could you please help me out

**Comment by shashank94** [comment]
Hi I'm too facing the same issue as @AfrinKhanam ,

I'm trying to train data from multiple files for composite entities. Currently I'm unable to do so and getting the following message - 'The CompositeEntityExtractor could not load the train file.'.

Please let me know if in case there is any alternate method or way to train the data from multiple files for composite entities.

Thanks in advance.

**Comment by BeWe11** [comment]
I'm aware that the component currently only works with single train file workflows. It shouldn't be hard to fix, however I've never needed it myself.

Can you tell me whether you are training via the training script or via the http server? Things are a bit more complicated for http training.

I don't have too much time currently, *maybe* I can fix this in 1 or 2 weeks. If you feel like helping me out, the lines you'd have to change are [https://github.com/BeWe11/rasa_composite_entities/blob/bd1cdd38b7e49b2433d4121a090a1edf200e9699/rasa_composite_entities/composite_entity_extractor.py#L40-L43](url) and [https://github.com/BeWe11/rasa_composite_entities/blob/bd1cdd38b7e49b2433d4121a090a1edf200e9699/rasa_composite_entities/composite_entity_extractor.py#L62-L80](url). The only change necessary is to anticipate multiple files and combine the composite entity definitions from all files.

**Comment by AfrinKhanam** [comment]
Hi, Thanks for the reply.
I'm training files via training script. Could you please help me out with this?

**Comment by BeWe11** [comment]
I will fix this next week. Stay tuned.

**Comment by AfrinKhanam** [comment]
ya sure @BeWe11 ..Thank you

**Comment by BeWe11** [comment]
Fixed by https://github.com/BeWe11/rasa_composite_entities/commit/35d9bed91ff02126e79390f7c799b258adbeefbd. You can fetch the latest pip release.
