### ISSUE TITLE
Training doesn’t work with Rasa X

### ISSUE THREAD

**Issue by BeWe11** [BeWe11/rasa_composite_entities#6]
Rasa X does not support using JSON files directly. JSON can only be imported via the UI, but in that case the composite patterns are stripped and a markdown file is being saved. So as for now, training this component is not possible using the rasa X UI.

Training using the command line scripts (`rasa train` and `rasa train nlu`) works fine.

**Comment by JulianGerhard21** [comment]
@BeWe11 

Is it planned to support markdown in the future? For the sake of simplicity with the entities, we currently use markdown, but we want to use your extension... do we simply need to convert it?

**Comment by BeWe11** [comment]
Using markdown files is not supported right now. If you want to use this component, you have to convert your training data to JSON. I'm actually evaluating if I can include this component natively in rasa (see https://github.com/RasaHQ/rasa/issues/3765). That would include markdown compatibility.

**Comment by BeWe11** [comment]
Rasa X now supports using training files in JSON format!
